[versions]
opencsv = "5.12.0"
hibernate = "7.1.0.Final"
persistenceApi = "3.1.0"
hsqldb="2.7.4"

spring-dependency = "1.1.7"
sonar = "6.2.0.5505"
plugin-lombok-version ="8.14"
plugin-spotless-version ="7.2.1"
[libraries]
plugin-lombok={ group = "io.freefair.lombok", name = "io.freefair.lombok.gradle.plugin", version.ref = "plugin-lombok-version" }
plugin-spotless={ group = "com.diffplug.spotless", name = "com.diffplug.spotless.gradle.plugin", version.ref = "plugin-spotless-version" }
opencsv = { group = "com.opencsv", name = "opencsv", version.ref = "opencsv" }
hibernate-core = { group = "org.hibernate.orm", name = "hibernate-core", version.ref = "hibernate" }
jakarta-persistence-api = { group = "jakarta.persistence", name = "jakarta.persistence-api", version.ref = "persistenceApi" }
hsqldb = { group = "org.hsqldb", name = "hsqldb", version.ref = "hsqldb" }




[plugins]
sonar = { id = "org.sonarqube", version.ref = "sonar" }
spring-dependency = { id = "io.spring.dependency-management", version.ref = "spring-dependency" }

